//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class carros
    {
        [Key]
        public int id { get; set; }
        public Nullable<int> modelo { get; set; }
        public string marca { get; set; }
        public string kilometraje { get; set; }
        public Nullable<int> velocidad { get; set; }
        public string estado { get; set; }
        public string placa { get; set; }
        public Nullable<int> precio { get; set; }
    }
}
